### ISSUE TITLE
(might) not be working with latest paper MC 1.17 on release

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#549]
There was a starting error in console:
Since paper is not officially out yet for production, we will wait for this release. 

```
[22:33:32] [Server thread/WARN]: java.lang.NoClassDefFoundError: net/skinsrestorer/shared/exception/SkinRequestException
[22:33:32] [Server thread/WARN]:     at com.bgsoftware.superiorskyblock.hooks.SkinsRestorerHook.register(SkinsRestorerHook.java:39)
[22:33:32] [Server thread/WARN]:     at com.bgsoftware.superiorskyblock.handlers.ProvidersHandler.lambda$null$3(ProvidersHandler.java:100)
[22:33:32] [Server thread/WARN]:     at com.bgsoftware.superiorskyblock.handlers.ProvidersHandler.runSafe(ProvidersHandler.java:205)
[22:33:32] [Server thread/WARN]:     at com.bgsoftware.superiorskyblock.handlers.ProvidersHandler.lambda$loadData$24(ProvidersHandler.java:100)
[22:33:32] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[22:33:32] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[22:33:32] [Server thread/WARN]:     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1078)
[22:33:32] [Server thread/WARN]:     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[22:33:32] [Server thread/WARN]:     at java.base/java.lang.Thread.run(Thread.java:829)
[22:33:32] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: net.skinsrestorer.shared.exception.SkinRequestException
[22:33:32] [Server thread/WARN]:     at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153)
[22:33:32] [Server thread/WARN]:     at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114)
[22:33:32] [Server thread/WARN]:     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[22:33:32] [Server thread/WARN]:     ... 9 more 
```

**Comment by AlexProgrammerDE** [comment]
1.This is an issue because a plugins skinsrestorer dependency and the actually installed skinsrestorer being out of sync.
2. We fully support 1.17 at the moment
