### ISSUE TITLE
MySQL error: java.lang.NoClassDefFoundError: com/mysql/cj/jdbc/result/ResultSetMetaData

### ISSUE THREAD

**Issue by bundabrg** [SkinsRestorer/SkinsRestorerX#245]
## Describe the bug
Since upgrading to 13.7.7 (and above) MySQL fails with the following in the logs:
```
08:00:04 [INFO] [/xxx:43812] <-> InitialHandler has pinged
08:00:05 [INFO] [/1xxx:43814] <-> InitialHandler has connected
08:00:05 [INFO] [SkinsRestorer] MySQL error: java.lang.NoClassDefFoundError: com/mysql/cj/jdbc/result/ResultSetMetaData
08:00:05 [INFO] [SkinsRestorer] MySQL error: java.lang.NoClassDefFoundError: com/mysql/cj/jdbc/result/ResultSetMetaData
08:00:05 [INFO] [SkinsRestorer] MySQL error: java.lang.NoClassDefFoundError: com/mysql/cj/jdbc/result/ResultSetMetaData
08:00:05 [INFO] [SkinsRestorer] MySQL error: java.lang.NoClassDefFoundError: com/mysql/cj/jdbc/result/ResultSetMetaData
08:00:08 [SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@525d79f0, id=67, owner=skinsrestorer.bungee.SkinsRestorer@7015ebef, task=skinsrestorer.bungee.listeners.LoginListener$$Lambda$905/0x0000000840780440@58adc45c, delay=0, period=0, running=true) encountered an exception
java.lang.NoClassDefFoundError: skinsrestorer/shared/utils/MojangAPI$Property
        at skinsrestorer.shared.utils.MojangAPI.getSkinProperty(MojangAPI.java:55)
        at skinsrestorer.shared.utils.MojangAPI.getSkinProperty(MojangAPI.java:79)
        at skinsrestorer.shared.storage.SkinStorage.getOrCreateSkinForPlayer(SkinStorage.java:133)
        at skinsrestorer.shared.storage.SkinStorage.getOrCreateSkinForPlayer(SkinStorage.java:151)
        at skinsrestorer.bungee.SkinApplier.applySkin(SkinApplier.java:34)
        at skinsrestorer.bungee.listeners.LoginListener.lambda$onServerChange$0(LoginListener.java:49)
        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: skinsrestorer.shared.utils.MojangAPI$Property
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:63)
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:37)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 10 more

```

Happens when a player logs in. Will prevent them connecting.

Rolling back to 13.7.5 resolves it for me.

**Comment by xknat** [comment]
@bundabrg hi we have a template:
## Describe the bug
A clear and concise description of what the bug is.

## How can we reproduce what you got?
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**

**What version? Do NOT answer LATEST**
* SkinsRestorer: 13.
* Spigot version:
* Bungeecord version: 
* IF bungee, did you put the plugin on all servers: Yes / No
* Java: 8

## Logs
Replace the links below by a paste of your startup logs (if you run a **Bungeecord** server, please send startup logs from **Bungeecord *AND* Spigot/Bukkit**)
https://gist.github.com
https://hastebin.app

## Additional context
Add any other context about the problem here.

**Comment by bundabrg** [comment]
I'll close till I have time to put all the info. It's a missing classdef so fairly simple fix. I'll submit a PR as well.

**Comment by McLive** [comment]
Looks like your BungeeCord build doesn't ship the mysql lib.
But since it also can't find ``skinsrestorer/shared/utils/MojangAPI$Property`` it looks like either your SkinsRestorer or BungeeCord build is broken.
