### ISSUE TITLE
Error when starting velocity

### ISSUE THREAD

**Issue by XiYang6666** [SkinsRestorer/SkinsRestorerX#1711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

when I update SkinsRestorer to 15.3.0, there was an error:

```
[19:48:16 ERROR]: Couldn't pass ProxyInitializeEvent to skinsrestorer 15.3.0
java.lang.NoClassDefFoundError: xyz/wagyourtail/jvmdg/j16/stub/java_base/J_L_Record
        at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524) ~[?:?]
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427) ~[?:?]
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421) ~[?:?]
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:714) ~[?:?]
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:70) ~[velocity-3.3.0-SNAPSHOT-411.jar:3.3.0-SNAPSHOT (git-a4476253-b411)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[velocity-3.3.0-SNAPSHOT-411.jar:3.3.0-SNAPSHOT (git-a4476253-b411)]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.skinsrestorer.velocity.SRVelocityBootstrap.onProxyInitialize(SRVelocityBootstrap.java:53) ~[?:?]
        at net.skinsrestorer.velocity.Lmbda$1.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-SNAPSHOT-411.jar:3.3.0-SNAPSHOT (git-a4476253-b411)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity-3.3.0-SNAPSHOT-411.jar:3.3.0-SNAPSHOT (git-a4476253-b411)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity-3.3.0-SNAPSHOT-411.jar:3.3.0-SNAPSHOT (git-a4476253-b411)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ClassNotFoundException: xyz.wagyourtail.jvmdg.j16.stub.java_base.J_L_Record
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[velocity-3.3.0-SNAPSHOT-411.jar:3.3.0-SNAPSHOT (git-a4476253-b411)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[velocity-3.3.0-SNAPSHOT-411.jar:3.3.0-SNAPSHOT (git-a4476253-b411)]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 20 more
```

### How can we reproduce what you got?

1. Put SkinRestorer.jar to plugin folder
2. Start the Velocity

### Minecraft implementation

```markdown
- Proxy: Velocity
- Backend: Paper
```

### SkinsRestorer Version

15.3.0

### List of plugins

SkinsRestorer

### Java Version

"21.0.3" 2024-04-16 LTS

### Does your issue require a plugin in order to reproduce?

No

**Comment by AlexProgrammerDE** [comment]
Fixed with 15.3.1.
